
services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml:ro
    restart: unless-stopped
    logging:
      driver: awslogs
      options:
        awslogs-group: "loki-logs-group"
        awslogs-stream: "loki-logs"
        awslogs-region: "us-east-2"
